services:
  - type: web
    name: carrivo-model-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    autoDeploy: false
